[package]
name = "narwhal-crypto"
version = "0.1.0"
license = "Apache-2.0"
authors = ["Mysten Labs <build@mystenlabs.com>"]
edition = "2021"
publish = false

[dependencies]
fastcrypto.workspace = true
fastcrypto-tbls.workspace = true
serde.workspace = true
shared-crypto.workspace = true
bcs.workspace = true

[features]
default = []