[package]
name = "move-abigen"
version = "0.1.0"
authors = ["Diem Association <opensource@diem.com>"]
publish = false
edition = "2021"
license = "Apache-2.0"

[dependencies]
# Move dependencies
move-model.workspace = true
move-core-types.workspace = true
move-binary-format.workspace = true
move-bytecode-verifier.workspace = true
move-command-line-common.workspace = true

bcs.workspace = true

# external dependencies
log.workspace = true
anyhow.workspace = true
heck.workspace = true
serde.workspace = true

[dev-dependencies]
codespan-reporting.workspace = true
move-prover.workspace = true
datatest-stable.workspace = true
tempfile.workspace = true
move-prover-test-utils.workspace = true

[[test]]
name = "testsuite"
harness = false
