[package]
name = "sui-protocol-config"
version = "0.1.0"
authors = ["Mysten Labs <build@mystenlabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies]
serde.workspace = true
tracing.workspace = true
serde_with.workspace = true
sui-protocol-config-macros.workspace = true
schemars.workspace = true
insta.workspace = true
clap = { version = "4.3.2", features = ["derive"] }

[dev-dependencies]
insta.workspace = true
