[package]
name = "narwhal-utils"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
once_cell.workspace = true
futures.workspace = true
tracing.workspace = true
workspace-hack.workspace = true

