[package]
name = "move-read-write-set-types"
version = "0.0.3"
authors = ["Diem Association <opensource@diem.com>"]
description = "Type definition for read/write set inference for Move bytecode programs"
repository = "https://github.com/diem/diem"
homepage = "https://diem.com"
license = "Apache-2.0"
publish = ["crates-io"]
edition = "2021"

[dependencies]
move-binary-format.workspace = true
move-core-types.workspace = true
serde.workspace = true
