[package]
name = "move-vm-paranoid-tests"
version = "0.1.0"
authors = ["Diem Association <opensource@diem.com>"]
publish = false
edition = "2021"
license = "Apache-2.0"

[dev-dependencies]
fail = { workspace = true, features = ["failpoints"] }
datatest-stable.workspace = true
move-transactional-test-runner = { workspace = true, features = ['failpoints'] }

[[test]]
name = "tests"
harness = false

[dependencies]
