[package]
name = "spec-flatten"
version = "0.1.0"
authors = ["Diem Association <opensource@diem.com>"]
description = "Formal specification flattening tool"
publish = false
edition = "2021"
license = "Apache-2.0"

[dependencies]

# move dependencies
move-stackless-bytecode.workspace = true
move-compiler.workspace = true
move-model.workspace = true
move-prover.workspace = true

# external dependencies
anyhow.workspace = true
itertools.workspace = true
pretty.workspace = true
clap.workspace = true
