name: DSN sequencer

on:
  push:
    branches:
      - 'master'
    tags:
      - '*.*.*'
  pull_request:
    branches:
      - 'master'

jobs:
  build:
    name: Build and push docker image
    runs-on: ubuntu-latest
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
      DOCKER_REGISTRY: ghcr.io
      DOCKER_IMAGE_BASE: ${{ github.repository_owner }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to the registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Tags and label image
        id: meta-sequencer
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_IMAGE_BASE }}/sequencer

      - name: Build and push image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: docker/sequencer/Dockerfile
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: ${{ steps.meta-sequencer.outputs.tags }}
          labels: ${{ steps.meta-sequencer.outputs.labels }}